agents:
  queue: derecho
  modules: climacommon
  pbs_q: preempt
  pbs_l_select: "1:ngpus=1:ncpus=1" # We are out of CPU-only hours...

env:
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project"
      - julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - echo "--- Instantiate SurfaceFluxes calibration project"
      - julia --project=experiments/surface_fluxes_perfect_model -e 'using Pkg; Pkg.instantiate(;verbose=true)'

  - wait

  - label: "SurfaceFluxes perfect model calibration"
    command: 
    - echo "--- WorkerBackend Calibration" 
    - julia --project=experiments/surface_fluxes_perfect_model test/worker_backend.jl
    - rm -rf output/surface_fluxes_perfect_model/*
    - echo "--- HPCBackend Calibration" 
    - julia --project=experiments/surface_fluxes_perfect_model test/hpc_backend.jl
    artifact_paths: output/surface_fluxes_perfect_model/*

  - label: "PBS job controller unit tests"
    command: julia --project=experiments/surface_fluxes_perfect_model test/pbs_unit_tests.jl

  - label: "PBSManager tests"
    command: julia --project=experiments/surface_fluxes_perfect_model test/pbs_manager_unit_tests.jl
