agents:
  queue: derecho
  modules: climacommon/2024_05_27
   
env:
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate SurfaceFluxes calibration project"
      - julia -e 'sleep(600)'
    agents:
      pbs_q: develop
      pbs_l_select: "1:ncpus=1"
      pbs_l_walltime: "00:05:00"
