agents:
  slurm_partition: broken
  slurm_arg: invalid
  architecture: GPU
  queue: clima
  modules: test test

env:
  JULIA_MPI_HAS_CUDA: "true"
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GRES_FLAGS: "allow-task-sharing"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate SurfaceFluxes calibration project"
      - julia --project=experiments/surface_fluxes_perfect_model -e 'using Pkg; Pkg.precompile()'

  - wait
  - label: "SurfaceFluxes perfect model calibration"
    command: julia --project=experiments/surface_fluxes_perfect_model test/hpc_backend_e2e.jl
    artifact_paths: output/surface_fluxes_perfect_model/*
    agents: 
      slurm_partition: broken
      slurm_arg: invalid
      modules: test test
    
  - label: "Slurm job controller unit tests"
    command: julia --project=experiments/surface_fluxes_perfect_model test/slurm_unit_tests.jl
