agents:
  queue: clima
  modules: julia/1.11.0 cuda/julia-pref openmpi/4.1.5-mpitrampoline nsight-systems/2024.6.1

env:
  JULIA_MPI_HAS_CUDA: "true"
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  SLURM_GRES_FLAGS: "allow-task-sharing"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project"
      - julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - echo "--- Instantiate SurfaceFluxes calibration project"
      - julia --project=experiments/surface_fluxes_perfect_model -e 'using Pkg; Pkg.instantiate(;verbose=true)'

  - wait

  - label: "SurfaceFluxes perfect model calibration"
    command: 
    - julia --project=experiments/surface_fluxes_perfect_model test/worker_backend.jl
    - rm -rf output/surface_fluxes_perfect_model/*
    - julia --project=experiments/surface_fluxes_perfect_model test/hpc_backend.jl
    artifact_paths: output/surface_fluxes_perfect_model/*
    agents:
      slurm_ntasks: 5
      slurm_cpus_per_task: 1

  - label: "Slurm job controller unit tests"
    command: julia --project=experiments/surface_fluxes_perfect_model test/slurm_unit_tests.jl

  - label: "SlurmManager tests"
    command: julia --project=experiments/surface_fluxes_perfect_model test/slurm_manager_unit_tests.jl
    agents:
      slurm_ntasks: 2
      slurm_cpus_per_task: 1
