name: ci
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

# Needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

# A force-push should not leave a full matrix running on the superseded commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: ci ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      # One failing job should not hide the results of the others
      fail-fast: false
      matrix:
        version:
          # The minimum version declared in Project.toml, so that the compat
          # bound is tested
          - '1.10'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
        exclude:
          # Nightly on one platform is enough to catch upstream breakage
          - version: 'nightly'
            os: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        # Coverage from one entry in the matrix is enough
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest'
        with:
          files: lcov.info
          token: ${{secrets.CODECOV_TOKEN}}
