name: ci
on:
  push:
    branches:
      - main
      - trying
      - staging
    tags: '*'
  pull_request:

# Needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    name: ci ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        version:
          - '1.11'
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      # CalibrateEmulateSample relies on Python modules
      # We retry this step because the first install is flaky
      - uses: nick-fields/retry@v3
        with:
          max_attempts: 2
          timeout_minutes: 10
          command: |
            julia --color=yes --project=test -e 'using Pkg; Pkg.instantiate()'
            julia --project=test -e 'using Conda; Conda.add("scipy=1.14.1"); Conda.add("scikit-learn=1.5.1")'
        env: 
          PYTHON: ""
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          token: ${{secrets.CODECOV_TOKEN}}